# Generated by Django 3.0.5 on 2020-04-27 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200426_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmation_handling_sensitive_data',
            new_name='Confirmacion_manejo_datos_sensibles',
        ),
    ]
