# Generated by Django 3.0.5 on 2020-05-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200427_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_administrador',
            new_name='Administrador',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_egresado',
            new_name='Egresado',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_superusuario',
            new_name='Superusuario',
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
    ]
