# Generated by Django 3.0.5 on 2020-05-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200502_2346'),
        ('users', '0005_auto_20200501_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias', to='posts.Interes', verbose_name='Categorías'),
        ),
    ]
