# Generated by Django 2.2.6 on 2020-05-12 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200512_1155'),
        ('users', '0006_user_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='accounts.Follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
