# Generated by Django 3.0.5 on 2020-05-02 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_interes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interes',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='interes',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
