# Generated by Django 3.0.5 on 2020-05-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200501_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interes',
            field=models.ManyToManyField(to='posts.Interes'),
        ),
    ]
