# Generated by Django 3.0.5 on 2020-05-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200502_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='interes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Interes'),
        ),
    ]
