# Generated by Django 3.0.5 on 2020-05-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200502_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='interes',
        ),
        migrations.AddField(
            model_name='post',
            name='interes',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
