# Generated by Django 3.0.5 on 2020-05-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200502_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interes',
            options={'verbose_name': 'categoría', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(to='posts.Interes', verbose_name='Categorías'),
        ),
    ]
