# Generated by Django 2.2.6 on 2020-06-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_egresados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Egresados',
            new_name='DBEgresado',
        ),
    ]
